name: API Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  functional:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm install
      - name: Functional tests
        run: npm run test:dev
      - name: Upload functional report
        uses: actions/upload-artifact@v4
        with:
          name: functional-report
          path: reports/

  security:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm install
      - name: Security tests
        run: npx newman run tests/api/collections/security-tests.json -e tests/api/environments/dev.json

  performance:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - name: Performance tests (k6)
        uses: grafana/k6-action@v0.3.0
        with:
          filename: tests/performance/load-test.js
          flags: --out json=reports/performance-metrics.json
      - name: Upload performance report
        uses: actions/upload-artifact@v4
        with:
          name: performance-metrics
          path: reports/performance-metrics.json

  dashboard:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm install
      - name: Generate Dashboard
        run: node scripts/generate-dashboard.js
      - name: Upload Dashboard artifact
        uses: actions/upload-artifact@v4
        with:
          name: dashboard
          path: docs/

  notify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm install
      - name: Send email notification (Ethereal)
        run: node scripts/email-notifier.js

  slack-notification:
    runs-on: ubuntu-latest
    needs: [functional, dashboard, notify]
    if: always()
    steps:
      - name: Send Slack notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_USERNAME: "API Tests Bot"
          SLACK_TITLE: "Résultats des tests API"
          SLACK_MESSAGE: |
            Functional: ${{ needs.functional.result }}
            Security: ${{ needs.security.result }}
            Performance: ${{ needs.performance.result }}
            Dashboard: ${{ needs.dashboard.result }}
            Report: https://github.com/User288-wq/api-testing-demo/actions/runs/${{ github.run_id }}
          SLACK_COLOR: ${{ contains(needs.*.result, 'failure') && 'danger' || 'good' }}
          SLACK_FOOTER: "Déclenché par ${{ github.actor }}"
